[project]
authors = ["Ollie <buitelaarolivier@gmail.com>"]
channels = ["conda-forge"]
name = "rules-maker"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.8"
requests = "*"
beautifulsoup4 = "*"
pydantic = "*"
click = "*"
pyyaml = "*"
