[project]
authors = ["Ollie <buitelaarolivier@gmail.com>"]
channels = ["conda-forge"]
name = "rules-maker"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.8"
requests = "*"
beautifulsoup4 = "*"
pydantic = "*"
click = "*"
pyyaml = "*"
numpy = ">=2.3.2,<3"
scikit-learn = ">=1.7.1,<2"
jinja2 = ">=3.1.6,<4"
boto3 = ">=1.40.21,<2"
pytest = "*"
pytest-asyncio = "*"
