sources:
- framework: fastapi
  name: FastAPI
  technology: python
  url: https://fastapi.tiangolo.com/
- framework: react
  name: React
  technology: javascript
  url: https://react.dev/learn
- framework: vue
  name: Vue.js
  technology: javascript
  url: https://vuejs.org/guide/
- framework: django
  name: Django
  technology: python
  url: https://www.djangoproject.com/
- framework: django-rest-framework
  name: Django REST Framework
  technology: python
  url: https://www.django-rest-framework.org/
- framework: nextjs
  name: Next.js
  technology: javascript
  url: https://nextjs.org/
- framework: gatsby
  name: Gatsby
  technology: javascript
  url: https://www.gatsbyjs.com/
- framework: nuxtjs
  name: Nuxt.js
  technology: javascript
  url: https://www.nuxtjs.org/
- framework: svelte
  name: Svelte
  technology: javascript
  url: https://www.svelte.dev/
- framework: sveltekit
  name: SvelteKit
  technology: javascript
  url: https://www.sveltekit.dev/
- framework: react
  name: React Official
  technology: javascript
  url: https://reactjs.org/
- name: JavaScript Info
  technology: javascript
  url: https://javascript.info/
- name: TypeScript
  technology: typescript
  url: https://www.typescriptlang.org/
- name: Python Official
  technology: python
  url: https://www.python.org/
- name: Ollama
  technology: ai
  url: https://ollama.com/
- framework: tensorflow
  name: TensorFlow
  technology: python
  url: https://www.tensorflow.org/
- framework: pytorch
  name: PyTorch
  technology: python
  url: https://www.pytorch.org/
- framework: scikit-learn
  name: Scikit-learn
  technology: python
  url: https://www.scikit-learn.org/stable/
- framework: nltk
  name: NLTK
  technology: python
  url: https://www.nltk.org/
- name: OpenAI
  technology: ai
  url: https://www.openai.com/
- name: Anthropic
  technology: ai
  url: https://www.anthropic.com/
- framework: boto3
  name: Boto3
  technology: python
  url: https://boto3.amazonaws.com/v1/documentation/api/latest/index.html
- framework: pydantic
  name: Pydantic
  technology: python
  url: https://www.pydantic.dev
- framework: transformers
  name: Hugging Face Transformers
  technology: python
  url: https://huggingface.co/docs/transformers/index
- framework: click
  name: Click
  technology: python
  url: https://click.palletsprojects.com/
- framework: rich
  name: Rich
  technology: python
  url: https://rich.readthedocs.io/
- framework: httpx
  name: HTTPX
  technology: python
  url: https://www.python-httpx.org/
- framework: fake-useragent
  name: Fake UserAgent
  technology: python
  url: https://fake-useragent.readthedocs.io/
- name: JSON Schema
  technology: json
  url: https://json-schema.org/
- framework: more-itertools
  name: More Itertools
  technology: python
  url: https://more-itertools.readthedocs.io/
- framework: sentence-transformers
  name: Sentence Transformers
  technology: python
  url: https://sbert.net/
- framework: transformers
  name: Hugging Face Transformers Docs
  technology: python
  url: https://huggingface.co/docs/transformers/
- framework: tokenizers
  name: Hugging Face Tokenizers
  technology: python
  url: https://huggingface.co/docs/tokenizers/
- framework: angular
  name: Angular
  technology: typescript
  url: https://angular.io/docs
- name: MDN JavaScript
  technology: javascript
  url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
- framework: webpack
  name: Webpack
  technology: javascript
  url: https://webpack.js.org/
- framework: vite
  name: Vite
  technology: javascript
  url: https://vitejs.dev/
- framework: parcel
  name: Parcel
  technology: javascript
  url: https://parceljs.org/
- framework: rollup
  name: Rollup
  technology: javascript
  url: https://rollupjs.org/
- framework: babel
  name: Babel
  technology: javascript
  url: https://babeljs.io/docs/
- framework: eslint
  name: ESLint
  technology: javascript
  url: https://eslint.org/docs/
- framework: prettier
  name: Prettier
  technology: javascript
  url: https://prettier.io/docs/
- framework: jest
  name: Jest
  technology: javascript
  url: https://jestjs.io/docs/
- framework: testing-library
  name: Testing Library
  technology: javascript
  url: https://testing-library.com/
- framework: storybook
  name: Storybook
  technology: javascript
  url: https://storybook.js.org/docs/
- framework: ember
  name: Ember.js
  technology: javascript
  url: https://emberjs.com/
- framework: nodejs
  name: Node.js
  technology: javascript
  url: https://nodejs.org/en/docs/
- framework: express
  name: Express.js
  technology: javascript
  url: https://expressjs.com/
- framework: koa
  name: Koa.js
  technology: javascript
  url: https://koajs.com/
- framework: socketio
  name: Socket.IO
  technology: javascript
  url: https://socket.io/docs/
- framework: passport
  name: Passport.js
  technology: javascript
  url: https://www.passportjs.org/docs/
- framework: mongoose
  name: Mongoose
  technology: javascript
  url: https://mongoosejs.com/docs/
- framework: sequelize
  name: Sequelize
  technology: javascript
  url: https://sequelize.org/docs/
- name: MDN CSS
  technology: css
  url: https://developer.mozilla.org/en-US/docs/Web/CSS
- framework: tailwind
  name: Tailwind CSS
  technology: css
  url: https://tailwindcss.com/docs
- framework: bootstrap
  name: Bootstrap
  technology: css
  url: https://getbootstrap.com/docs/
- framework: sass
  name: Sass
  technology: css
  url: https://sass-lang.com/documentation/
- framework: styled-components
  name: Styled Components
  technology: javascript
  url: https://styled-components.com/docs/
- framework: emotion
  name: Emotion
  technology: javascript
  url: https://emotion.sh/docs/
- framework: bulma
  name: Bulma
  technology: css
  url: https://bulma.io/documentation/
- name: Flask Palletsprojects
  technology: typescript
  url: https://flask.palletsprojects.com/
- name: Docs Sqlalchemy
  technology: unknown
  url: https://docs.sqlalchemy.org/
- name: Celery Readthedocs
  technology: unknown
  url: https://celery.readthedocs.io/
- name: Tornado Readthedocs
  technology: unknown
  url: https://tornado.readthedocs.io/
- name: Docs Aiohttp
  technology: unknown
  url: https://docs.aiohttp.org/
- name: Bottlepy
  technology: python
  url: https://bottlepy.org/docs/
- name: Falconframework
  technology: unknown
  url: https://falconframework.org/
- name: Numpy
  technology: python
  url: https://numpy.org/doc/
- name: Pandas Pydata
  technology: python
  url: https://pandas.pydata.org/docs/
- name: Matplotlib
  technology: unknown
  url: https://matplotlib.org/stable/
- name: Seaborn Pydata
  technology: python
  url: https://seaborn.pydata.org/
- name: Plotly
  technology: python
  url: https://plotly.com/python/
- name: Docs Scipy
  technology: python
  url: https://docs.scipy.org/
- name: Scikit Image
  technology: unknown
  url: https://scikit-image.org/docs/
- name: Xgboost Readthedocs
  technology: unknown
  url: https://xgboost.readthedocs.io/
- name: Lightgbm Readthedocs
  technology: unknown
  url: https://lightgbm.readthedocs.io/
- name: Statsmodels
  technology: typescript
  url: https://statsmodels.org/stable/
- name: Spacy
  technology: unknown
  url: https://spacy.io/
- name: Gensim Readthedocs
  technology: unknown
  url: https://gensim.readthedocs.io/
- name: Spring
  technology: typescript
  url: https://spring.io/projects/spring-framework
- name: Spring
  technology: typescript
  url: https://spring.io/projects/spring-boot
- name: Hibernate
  technology: unknown
  url: https://hibernate.org/orm/documentation/
- name: Micronaut
  technology: unknown
  url: https://micronaut.io/documentation/
- name: Quarkus
  technology: unknown
  url: https://quarkus.io/guides/
- name: Vertx
  technology: unknown
  url: https://vertx.io/docs/
- name: Developer Android
  technology: unknown
  url: https://developer.android.com/docs
- name: Kotlinlang
  technology: unknown
  url: https://kotlinlang.org/docs/
- name: Developer Apple
  technology: unknown
  url: https://developer.apple.com/documentation/swift/
- name: Developer Apple
  technology: unknown
  url: https://developer.apple.com/documentation/
- framework: react
  name: Reactnative
  technology: javascript
  url: https://reactnative.dev/docs/
- name: Flutter
  technology: unknown
  url: https://flutter.dev/docs
- name: Ionicframework
  technology: unknown
  url: https://ionicframework.com/docs/
- name: Docs Microsoft
  technology: unknown
  url: https://docs.microsoft.com/en-us/dotnet/
- name: Docs Microsoft
  technology: unknown
  url: https://docs.microsoft.com/en-us/aspnet/core/
- name: Docs Microsoft
  technology: unknown
  url: https://docs.microsoft.com/en-us/dotnet/csharp/
- name: Docs Microsoft
  technology: unknown
  url: https://docs.microsoft.com/en-us/ef/core/
- name: Unity
  technology: unknown
  url: https://unity.com/learn
- name: Dev Mysql
  technology: unknown
  url: https://dev.mysql.com/doc/
- name: Postgresql
  technology: unknown
  url: https://www.postgresql.org/docs/
- name: Docs Mongodb
  technology: unknown
  url: https://docs.mongodb.com/
- name: Redis
  technology: unknown
  url: https://redis.io/documentation
- name: Elastic Co
  technology: unknown
  url: https://www.elastic.co/guide/
- name: Neo4J
  technology: unknown
  url: https://neo4j.com/docs/
- name: Sqlite
  technology: unknown
  url: https://sqlite.org/docs.html
- name: Docs Docker
  technology: unknown
  url: https://docs.docker.com/
- name: Kubernetes
  technology: unknown
  url: https://kubernetes.io/docs/
- name: Docs Ansible
  technology: unknown
  url: https://docs.ansible.com/
- name: Terraform
  technology: unknown
  url: https://www.terraform.io/docs/
- name: Docs Aws Amazon
  technology: unknown
  url: https://docs.aws.amazon.com/
- name: Cloud Google
  technology: unknown
  url: https://cloud.google.com/docs/
- name: Docs Microsoft
  technology: unknown
  url: https://docs.microsoft.com/en-us/azure/
- name: Docs Gitlab
  technology: unknown
  url: https://docs.gitlab.com/
- name: Docs Github
  technology: unknown
  url: https://docs.github.com/
- name: Docs Pytest
  technology: python
  url: https://docs.pytest.org/
- name: Selenium Python Readthedocs
  technology: python
  url: https://selenium-python.readthedocs.io/
- name: Playwright
  technology: unknown
  url: https://playwright.dev/docs/
- name: Mochajs
  technology: javascript
  url: https://mochajs.org/
- name: Cypress
  technology: unknown
  url: https://www.cypress.io/
- name: Webdriver
  technology: unknown
  url: https://webdriver.io/docs/
- name: Ruby Lang
  technology: unknown
  url: https://www.ruby-lang.org/en/documentation/
- name: Rubyonrails
  technology: unknown
  url: https://rubyonrails.org/
- name: Golang
  technology: unknown
  url: https://golang.org/doc/
- name: Doc Rust Lang
  technology: unknown
  url: https://doc.rust-lang.org/
- name: Elixir Lang
  technology: unknown
  url: https://elixir-lang.org/docs.html
- name: Php
  technology: unknown
  url: https://www.php.net/docs.php
- name: Laravel
  technology: unknown
  url: https://laravel.com/docs/
- name: Symfony
  technology: unknown
  url: https://symfony.com/doc/
- name: Scala Lang
  technology: unknown
  url: https://www.scala-lang.org/documentation/
- name: Clojure
  technology: unknown
  url: https://clojure.org/
- name: Lua
  technology: unknown
  url: https://www.lua.org/docs.html
- name: R Project
  technology: unknown
  url: https://www.r-project.org/other-docs.html
- name: Docs Godotengine
  technology: unknown
  url: https://docs.godotengine.org/
- name: Pygame
  technology: python
  url: https://www.pygame.org/docs/
- name: Phaser
  technology: unknown
  url: https://phaser.io/learn
- name: Threejs
  technology: javascript
  url: https://threejs.org/docs/
- name: Swagger
  technology: unknown
  url: https://swagger.io/docs/
- name: Postman
  technology: unknown
  url: https://www.postman.com/api-platform/
- name: Stoplight
  technology: unknown
  url: https://stoplight.io/
- name: Readme
  technology: unknown
  url: https://readme.com/
- name: Docusaurus
  technology: unknown
  url: https://docusaurus.io/
- name: Docsify Js
  technology: javascript
  url: https://docsify.js.org/
- name: Git Scm
  technology: unknown
  url: https://git-scm.com/doc
- name: Gradle
  technology: unknown
  url: https://gradle.org/docs/
- name: Maven Apache
  technology: unknown
  url: https://maven.apache.org/guides/
- name: Ethereum
  technology: unknown
  url: https://ethereum.org/developers/docs/
- name: Docs Soliditylang
  technology: unknown
  url: https://docs.soliditylang.org/
- name: Docs Ethers
  technology: unknown
  url: https://docs.ethers.io/
- name: Strapi
  technology: unknown
  url: https://strapi.io/documentation/
- name: Docs Nestjs
  technology: javascript
  url: https://docs.nestjs.com/
- name: Remix Run
  technology: unknown
  url: https://remix.run/docs/
- name: Apollographql
  technology: unknown
  url: https://www.apollographql.com/docs/
- name: Graphql
  technology: unknown
  url: https://graphql.org/learn/
- name: Prisma
  technology: unknown
  url: https://www.prisma.io/docs/
- name: Trpc
  technology: unknown
  url: https://trpc.io/docs/
- name: Tanstack
  technology: unknown
  url: https://tanstack.com/query/latest
- name: Zustand Docs Pmnd Rs
  technology: unknown
  url: https://zustand.docs.pmnd.rs/
- name: Redux Js
  technology: javascript
  url: https://redux.js.org/
- name: Mobx Js
  technology: javascript
  url: https://mobx.js.org/README.html
- name: Recoiljs
  technology: javascript
  url: https://recoiljs.org/
- name: Framer
  technology: unknown
  url: https://www.framer.com/motion/
- name: Chakra Ui
  technology: unknown
  url: https://chakra-ui.com/docs/
- name: Mui
  technology: unknown
  url: https://mui.com/
- name: Ant Design
  technology: unknown
  url: https://ant.design/docs/
- name: Mantine
  technology: unknown
  url: https://mantine.dev/
- name: Ui Shadcn
  technology: unknown
  url: https://ui.shadcn.com/
- name: Headlessui
  technology: unknown
  url: https://headlessui.com/
- name: Radix Ui
  technology: unknown
  url: https://www.radix-ui.com/
- name: Requests Readthedocs
  technology: typescript
  url: https://requests.readthedocs.io/
- name: Docs Python
  technology: python
  url: https://docs.python.org/3/library/asyncio.html
- name: Jinja Palletsprojects
  technology: typescript
  url: https://jinja.palletsprojects.com/
- name: Marshmallow Readthedocs
  technology: unknown
  url: https://marshmallow.readthedocs.io/
- name: Alembic Sqlalchemy
  technology: unknown
  url: https://alembic.sqlalchemy.org/
- name: Fastapi Tiangolo
  technology: unknown
  url: https://fastapi.tiangolo.com/advanced/
- name: Strawberry Rocks
  technology: unknown
  url: https://strawberry.rocks/
- name: Graphene Python
  technology: python
  url: https://graphene-python.org/
- name: Black Readthedocs
  technology: unknown
  url: https://black.readthedocs.io/
- name: Flake8 Pycqa
  technology: python
  url: https://flake8.pycqa.org/
- name: Mypy Readthedocs
  technology: python
  url: https://mypy.readthedocs.io/
- name: Coverage Readthedocs
  technology: unknown
  url: https://coverage.readthedocs.io/
- name: Tox Readthedocs
  technology: unknown
  url: https://tox.readthedocs.io/
- name: Jenkins
  technology: unknown
  url: https://www.jenkins.io/doc/
- name: Concourse Ci
  technology: unknown
  url: https://concourse-ci.org/docs.html
- name: Spinnaker
  technology: unknown
  url: https://www.spinnaker.io/guides/
- name: Argoproj Github
  technology: unknown
  url: https://argoproj.github.io/
- name: Helm Sh
  technology: unknown
  url: https://helm.sh/docs/
- name: Istio
  technology: unknown
  url: https://istio.io/latest/docs/
- name: Prometheus
  technology: unknown
  url: https://prometheus.io/docs/
- name: Grafana
  technology: unknown
  url: https://grafana.com/docs/
- name: Docs Influxdata
  technology: unknown
  url: https://docs.influxdata.com/
- name: Clickhouse
  technology: unknown
  url: https://clickhouse.com/docs/
- name: Timescale
  technology: unknown
  url: https://www.timescale.com/docs/
- name: Docs Snowflake
  technology: unknown
  url: https://docs.snowflake.com/
- name: Cloud Google
  technology: unknown
  url: https://cloud.google.com/bigquery/docs
